{
 "title": "Local Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Deephaven", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Delay History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "Deephaven_DataLagWatcher_AELWatch",
     "legendFormat": "Audit Event Log"
    },
    {
     "expr": "Deephaven_DataLagWatcher_PELWatch",
     "legendFormat": "Process Event Log"
    }
   ]
  },
  {
   "title": "PEL Lag",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Deephaven_DataLagWatcher_PELWatch",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PEL Community",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Deephaven_DataLagWatcherCommunity_PELWatch",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Import Helper",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Deephaven_PQ_ImportHelperQuery{Deephaven_PQ_ImportHelperQuery=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MyEnterpriseScript",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Deephaven_PQ_MyEnterpriseScript{Deephaven_PQ_MyEnterpriseScript=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revert Helper",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Deephaven_PQ_RevertHelperQuery{Deephaven_PQ_RevertHelperQuery=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MyEnterpriseBatch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Deephaven_PQ_MyEnterpriseBatch{Deephaven_PQ_MyEnterpriseBatch=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AEL Lag",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Deephaven_DataLagWatcher_AELWatch",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AEL Community",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Deephaven_DataLagWatcherCommunity_AELWatch",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web Client Data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Deephaven_PQ_WebClientData{Deephaven_PQ_WebClientData=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MyCommunityScript",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Deephaven_PQ_MyCommunityScript{Deephaven_PQ_MyCommunityScript=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Controller History",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "Deephaven_Controller{Deephaven_Controller=\"Running\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "MyCommunityBatch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Deephaven_PQ_MyCommunityBatch{Deephaven_PQ_MyCommunityBatch=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Server History",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "Deephaven_Dispatcher_Query_1{Deephaven_Dispatcher_Query_1=\"Running\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Merge Server Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Deephaven_Dispatcher_Merge_1{Deephaven_Dispatcher_Merge_1=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Server Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Deephaven_Dispatcher_Query_1{Deephaven_Dispatcher_Query_1=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Controller Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Deephaven_Controller{Deephaven_Controller=\"Running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Merge Server History",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "Deephaven_Dispatcher_Merge_1{Deephaven_Dispatcher_Merge_1=\"Running\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Used Disk %",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})\n",
     "legendFormat": "Disk \"/\""
    }
   ]
  }
 ]
}